//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a7D.PDV.SATServiceTest.SAT_SERVICE_UI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAT_SERVICE_UI.ISAT")]
    public interface ISAT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/EnviarVenda", ReplyAction="http://tempuri.org/ISAT/EnviarVendaResponse")]
        a7D.PDV.SAT.SATServiceWCF.EnviarVendaResponse EnviarVenda(a7D.PDV.SAT.SATServiceWCF.EnviarVendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/EnviarVenda", ReplyAction="http://tempuri.org/ISAT/EnviarVendaResponse")]
        System.Threading.Tasks.Task<a7D.PDV.SAT.SATServiceWCF.EnviarVendaResponse> EnviarVendaAsync(a7D.PDV.SAT.SATServiceWCF.EnviarVendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/ConsultarStatus", ReplyAction="http://tempuri.org/ISAT/ConsultarStatusResponse")]
        string ConsultarStatus(int numeroSessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/ConsultarStatus", ReplyAction="http://tempuri.org/ISAT/ConsultarStatusResponse")]
        System.Threading.Tasks.Task<string> ConsultarStatusAsync(int numeroSessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/Log", ReplyAction="http://tempuri.org/ISAT/LogResponse")]
        string Log(string codigoAtivacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAT/Log", ReplyAction="http://tempuri.org/ISAT/LogResponse")]
        System.Threading.Tasks.Task<string> LogAsync(string codigoAtivacao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISATChannel : a7D.PDV.SATServiceTest.SAT_SERVICE_UI.ISAT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SATClient : System.ServiceModel.ClientBase<a7D.PDV.SATServiceTest.SAT_SERVICE_UI.ISAT>, a7D.PDV.SATServiceTest.SAT_SERVICE_UI.ISAT {
        
        public SATClient() {
        }
        
        public SATClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SATClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SATClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SATClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public a7D.PDV.SAT.SATServiceWCF.EnviarVendaResponse EnviarVenda(a7D.PDV.SAT.SATServiceWCF.EnviarVendaRequest request) {
            return base.Channel.EnviarVenda(request);
        }
        
        public System.Threading.Tasks.Task<a7D.PDV.SAT.SATServiceWCF.EnviarVendaResponse> EnviarVendaAsync(a7D.PDV.SAT.SATServiceWCF.EnviarVendaRequest request) {
            return base.Channel.EnviarVendaAsync(request);
        }
        
        public string ConsultarStatus(int numeroSessao) {
            return base.Channel.ConsultarStatus(numeroSessao);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarStatusAsync(int numeroSessao) {
            return base.Channel.ConsultarStatusAsync(numeroSessao);
        }
        
        public string Log(string codigoAtivacao) {
            return base.Channel.Log(codigoAtivacao);
        }
        
        public System.Threading.Tasks.Task<string> LogAsync(string codigoAtivacao) {
            return base.Channel.LogAsync(codigoAtivacao);
        }
    }
}
