//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace a7D.PDV.BLL.Ativacoes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsUtilSoap", Namespace="http://tempuri.org/")]
    public partial class wsUtil : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ErroOperationCompleted;
        
        private System.Threading.SendOrPostCallback CFEOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarNFEAoClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsUtil() {
            this.Url = "http://apipdvseven.azurewebsites.net/wsUtil.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ErroCompletedEventHandler ErroCompleted;
        
        /// <remarks/>
        public event CFECompletedEventHandler CFECompleted;
        
        /// <remarks/>
        public event EnviarNFEAoClienteCompletedEventHandler EnviarNFEAoClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Erro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Erro(string chaveAtivacao, string aplicacao, string versao, int idPDV, string codigo, [System.Xml.Serialization.XmlElementAttribute("erro")] string erro1, string stackTrace, string dados) {
            object[] results = this.Invoke("Erro", new object[] {
                        chaveAtivacao,
                        aplicacao,
                        versao,
                        idPDV,
                        codigo,
                        erro1,
                        stackTrace,
                        dados});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ErroAsync(string chaveAtivacao, string aplicacao, string versao, int idPDV, string codigo, string erro1, string stackTrace, string dados) {
            this.ErroAsync(chaveAtivacao, aplicacao, versao, idPDV, codigo, erro1, stackTrace, dados, null);
        }
        
        /// <remarks/>
        public void ErroAsync(string chaveAtivacao, string aplicacao, string versao, int idPDV, string codigo, string erro1, string stackTrace, string dados, object userState) {
            if ((this.ErroOperationCompleted == null)) {
                this.ErroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnErroOperationCompleted);
            }
            this.InvokeAsync("Erro", new object[] {
                        chaveAtivacao,
                        aplicacao,
                        versao,
                        idPDV,
                        codigo,
                        erro1,
                        stackTrace,
                        dados}, this.ErroOperationCompleted, userState);
        }
        
        private void OnErroOperationCompleted(object arg) {
            if ((this.ErroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ErroCompleted(this, new ErroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CFE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CFE(string destinatario, string nomeFantasia, string cnpj, string dataDe, string dataAte, string nomeArquivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bytesArquivo) {
            object[] results = this.Invoke("CFE", new object[] {
                        destinatario,
                        nomeFantasia,
                        cnpj,
                        dataDe,
                        dataAte,
                        nomeArquivo,
                        bytesArquivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CFEAsync(string destinatario, string nomeFantasia, string cnpj, string dataDe, string dataAte, string nomeArquivo, byte[] bytesArquivo) {
            this.CFEAsync(destinatario, nomeFantasia, cnpj, dataDe, dataAte, nomeArquivo, bytesArquivo, null);
        }
        
        /// <remarks/>
        public void CFEAsync(string destinatario, string nomeFantasia, string cnpj, string dataDe, string dataAte, string nomeArquivo, byte[] bytesArquivo, object userState) {
            if ((this.CFEOperationCompleted == null)) {
                this.CFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCFEOperationCompleted);
            }
            this.InvokeAsync("CFE", new object[] {
                        destinatario,
                        nomeFantasia,
                        cnpj,
                        dataDe,
                        dataAte,
                        nomeArquivo,
                        bytesArquivo}, this.CFEOperationCompleted, userState);
        }
        
        private void OnCFEOperationCompleted(object arg) {
            if ((this.CFECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CFECompleted(this, new CFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarNFEAoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarNFEAoCliente(DadosNfeCliente dados) {
            object[] results = this.Invoke("EnviarNFEAoCliente", new object[] {
                        dados});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarNFEAoClienteAsync(DadosNfeCliente dados) {
            this.EnviarNFEAoClienteAsync(dados, null);
        }
        
        /// <remarks/>
        public void EnviarNFEAoClienteAsync(DadosNfeCliente dados, object userState) {
            if ((this.EnviarNFEAoClienteOperationCompleted == null)) {
                this.EnviarNFEAoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarNFEAoClienteOperationCompleted);
            }
            this.InvokeAsync("EnviarNFEAoCliente", new object[] {
                        dados}, this.EnviarNFEAoClienteOperationCompleted, userState);
        }
        
        private void OnEnviarNFEAoClienteOperationCompleted(object arg) {
            if ((this.EnviarNFEAoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarNFEAoClienteCompleted(this, new EnviarNFEAoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosNfeCliente {
        
        private string cPFCNPJClienteField;
        
        private string nomeFantasiaEmissorField;
        
        private string chaveAcessoNFField;
        
        private string dataEmissaoField;
        
        private string numeroNotaField;
        
        private string valorTotalField;
        
        private string emailField;
        
        private string ufField;
        
        private string xMLBase64Field;
        
        /// <remarks/>
        public string CPFCNPJCliente {
            get {
                return this.cPFCNPJClienteField;
            }
            set {
                this.cPFCNPJClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFantasiaEmissor {
            get {
                return this.nomeFantasiaEmissorField;
            }
            set {
                this.nomeFantasiaEmissorField = value;
            }
        }
        
        /// <remarks/>
        public string ChaveAcessoNF {
            get {
                return this.chaveAcessoNFField;
            }
            set {
                this.chaveAcessoNFField = value;
            }
        }
        
        /// <remarks/>
        public string DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroNota {
            get {
                return this.numeroNotaField;
            }
            set {
                this.numeroNotaField = value;
            }
        }
        
        /// <remarks/>
        public string ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string XMLBase64 {
            get {
                return this.xMLBase64Field;
            }
            set {
                this.xMLBase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ErroCompletedEventHandler(object sender, ErroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ErroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CFECompletedEventHandler(object sender, CFECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EnviarNFEAoClienteCompletedEventHandler(object sender, EnviarNFEAoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarNFEAoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarNFEAoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591