/* 
 * PDVSeven API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace a7D.PDV.Integracao.API2.Model
{
    /// <summary>
    /// Cliente
    /// </summary>
    [DataContract]
    public partial class Cliente 
    {
        /// <summary>
        /// Sexo deste cliente
        /// </summary>
        /// <value>Sexo deste cliente</value>
        [DataMember(Name = "Sexo", EmitDefaultValue = false)]
        public string Sexo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Cliente" /> class.
        /// </summary>
        /// <param name="IDCliente">Chave primária deste cliente.</param>
        /// <param name="NomeCompleto">Nome completo deste cliente.</param>
        /// <param name="Telefone1DDD">DDD do telefone 1 deste cliente.</param>
        /// <param name="Telefone1Numero">Número do telefone 1 deste cliente.</param>
        /// <param name="Telefone2DDD">DDD do telefone 2 deste cliente.</param>
        /// <param name="Telefone2Numero">Número do telefone 2 deste cliente.</param>
        /// <param name="Documento1">Número do documento deste cliente.</param>
        /// <param name="Email">E-mail do cliente.</param>
        /// <param name="Endereco">Endereco.</param>
        /// <param name="Sexo">Sexo deste cliente.</param>
        /// <param name="DtNascimento">Data de nascimento deste cliente.</param>
        public Cliente(int? IDCliente = default(int?), string NomeCompleto = default(string), int? Telefone1DDD = default(int?), int? Telefone1Numero = default(int?), int? Telefone2DDD = default(int?), int? Telefone2Numero = default(int?), string Documento1 = default(string), string RG = default(string), string Email = default(string), ClienteEndereco Endereco = default(ClienteEndereco), string Sexo = default(string), DateTime? DtNascimento = default(DateTime?))
        {
            this.IDCliente = IDCliente;
            this.NomeCompleto = NomeCompleto;
            this.Telefone1DDD = Telefone1DDD;
            this.Telefone1Numero = Telefone1Numero;
            this.Telefone2DDD = Telefone2DDD;
            this.Telefone2Numero = Telefone2Numero;
            this.Documento1 = Documento1;
            this.RG = RG;
            this.Email = Email;
            this.Endereco = Endereco;
            this.Sexo = Sexo;
            this.DtNascimento = DtNascimento;
        }

        /// <summary>
        /// Chave primária deste cliente
        /// </summary>
        /// <value>Chave primária deste cliente</value>
        [DataMember(Name = "IDCliente", EmitDefaultValue = false)]
        public int? IDCliente { get; set; }
        /// <summary>
        /// Nome completo deste cliente
        /// </summary>
        /// <value>Nome completo deste cliente</value>
        [DataMember(Name = "NomeCompleto", EmitDefaultValue = false)]
        public string NomeCompleto { get; set; }
        /// <summary>
        /// DDD do telefone 1 deste cliente
        /// </summary>
        /// <value>DDD do telefone 1 deste cliente</value>
        [DataMember(Name = "Telefone1DDD", EmitDefaultValue = false)]
        public int? Telefone1DDD { get; set; }
        /// <summary>
        /// Número do telefone 1 deste cliente
        /// </summary>
        /// <value>Número do telefone 1 deste cliente</value>
        [DataMember(Name = "Telefone1Numero", EmitDefaultValue = false)]
        public int? Telefone1Numero { get; set; }
        /// <summary>
        /// DDD do telefone 2 deste cliente
        /// </summary>
        /// <value>DDD do telefone 2 deste cliente</value>
        [DataMember(Name = "Telefone2DDD", EmitDefaultValue = false)]
        public int? Telefone2DDD { get; set; }
        /// <summary>
        /// Número do telefone 2 deste cliente
        /// </summary>
        /// <value>Número do telefone 2 deste cliente</value>
        [DataMember(Name = "Telefone2Numero", EmitDefaultValue = false)]
        public int? Telefone2Numero { get; set; }
        /// <summary>
        /// Número do documento deste cliente
        /// </summary>
        /// <value>Número do documento deste cliente</value>
        [DataMember(Name = "Documento1", EmitDefaultValue = false)]
        public string Documento1 { get; set; }

        [DataMember(Name = "RG", EmitDefaultValue = false)]
        public string RG { get; set; }

        /// <summary>
        /// E-mail do cliente
        /// </summary>
        /// <value>E-mail do cliente</value>
        [DataMember(Name = "Email", EmitDefaultValue = false)]
        public string Email { get; set; }
        /// <summary>
        /// Gets or Sets Endereco
        /// </summary>
        [DataMember(Name = "Endereco", EmitDefaultValue = false)]
        public ClienteEndereco Endereco { get; set; }
        /// <summary>
        /// Data de nascimento deste cliente
        /// </summary>
        /// <value>Data de nascimento deste cliente</value>
        [DataMember(Name = "DtNascimento", EmitDefaultValue = false)]
        public DateTime? DtNascimento { get; set; }
    }
}
