USE PDV7
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRAN A
BEGIN TRY

IF NOT EXISTS (SELECT 1 FROM tbSTatusComanda WHERE IDStatusComanda = 50)
  begin
    INSERT INTO tbStatusComanda(IDStatusComanda, Nome) values (50, 'Conta solicitada')
  end

COMMIT TRAN A

END TRY
BEGIN CATCH 
  rollback TRAN A
  SELECT ERROR_MESSAGE() as 'ERROR_MESSAGE', ERROR_SEVERITY() as 'ERROR_SEVERITY', ERROR_STATE() as 'ERROR_STATE', ERROR_LINE() as 'ERROR_LINE', ERROR_PROCEDURE() as 'ERROR_PROCEDURE'
END CATCH