// <auto-generated />
namespace a7D.PDV.Gateway.UIWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InformacoesPedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InformacoesPedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201607212127037_InformacoesPedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
