namespace a7D.PDV.Fiscal.Comunicacao.SAT
{
    public static class CodigosSAT
    {
        //Códigos extraidos de:
        // http://bematechpartners.com.br/wiki/index.php/2017/09/01/1517/
        public static string DescricoesOuCodigos(string codigo)
        {
            string[] codigos = codigo.Split('|');
            string retorno = "";
            foreach (var cod in codigos)
                retorno += Descricao(cod) + "\r\n";

            return retorno;
        }

        public static string Descricao(string codigo)
        {
            if (string.IsNullOrEmpty(codigo))
                return "";

            else if (int.TryParse(codigo, out int valor))
            {
                if (valor == 0)
                    return "";

                codigo = valor.ToString();
            }

            for (int n = 0; n < descricoes.Length; n += 2)
            {
                if (codigo == descricoes[n])
                    return $"[{codigo}] {descricoes[n + 1].Split('\t')[0]}";
            }
            return codigo;
        }

        private static string[] descricoes = {
            "1004", "Validacao se o leiaute esta dentre os aceitos pelo SAT	Rejeicao: Versao do leiaute do arquivo de entrada do SAT nao e valida",
            "1005", "Validacao se o leiaute de entrada esta dentre os aceitos pelo SAT, porem nao e a atual	Alerta: Versao do leiaute do arquivo de entrada do SAT nao e a mais atual",
            "1019", "Validacao se numeracao dos itens e crescente	Rejeicao: numeracao dos itens nao e sequencial crescente",
            "1073", "Se informada TAG, validacao de numero positivo ou igual a zero.	Rejeicao: Valor de Desconto sobre total nao e maior ou igual a zero.",
            "1074", "Se informada TAG, validacao de numero positivo ou igual a zero.	Rejeicao: Valor de Acrescimo sobre total nao e maior ou igual a zero.",
            "1084", "Formato do Certificado Invalido	Erro Formatacao do Certificado nao e valido.",
            "1203", "CNPJ do emitente nao corresponde ao contribuinte autorizado para uso do SAT	Rejeicao: Emitente nao autorizado para uso do SAT.",
            "1207", "CNPJ do emitente:com zeros, nulo ou DV invalido.	Rejeicao: CNPJ do emitente invalido",
            "1220", "Valor do rateio do Desconto sobre subtotal nao e maior que zero	Rejeicao: Valor do rateio do desconto sobre subtotal do item (N) invalido.",
            "1224", "CNPJ com zeros, nulo ou DV invalido	Rejeicao: CNPJ da Software House invalido",
            "1226", "Codigo da UF do Emitente diverge da UF receptora.	Rejeicao: Codigo da UF do Emitente diverge da UF receptora.",
            "1228", "Valor do rateio do acrescimo sobre subtotal nao e maior que zero	Rejeicao: Valor do rateio do acrescimo sobre subtotal do item (N) invalido.",
            "1229", "IE Emitente com zeros ou nulo	Rejeicao: IE do emitente nao informada",
            "1230", "IE nao corresponde ao Contribuinte de uso do SAT	Rejeicao: IE do emitente diferente da IE do contribuinte autorizado para uso do SAT",
            "1235", "CNPJ do destinatario com zeros, digito de controle invalido ou igual ao do emitente do CF-e-SAT	Rejeicao: CNPJ do destinatario invalido",
            "1237", "E03 CPF do destinatario com zeros ou digito de controle invalido	Rejeicao: CPF do destinatario invalido",
            "1258", "Validacao se data/hora e anterior a data/hora do ultimo CF-e-SAT emitido ou cancelado	Rejeicao: Data/hora invalida. Problemas com o relogio interno do SAT-CF-e",
            "1287", "Validacao se Codigo do Municipio do FG - ISSQN com digito invalido. Exceto os codigos descritos no Anexo 2 que apresentam digito invalido.	Rejeicao: Codigo Municipio do FG -ISSQN: digito invalido. Exceto os codigos descritos no Anexo 2 que apresentam digito invalido.",
            "1408", "Validacao se totalizador menor ou igual ao somatorio dos valores de Meio de Pagamento (id:VA03)	Rejeicao: Valor total do CF-e-SAT maior que o somatorio dos valores de Meio de Pagamento empregados em seu pagamento.",
            "1409", "Validacao se conteudo menor ou igual ao maximo permitido no arquivo de Parametrizacao de Uso	Rejeicao: Valor total do CF-e-SAT supera o maximo permitido no arquivo de Parametrizacao de Uso",
            "1450", "Validacao se Codigo diferente de 59	Rejeicao: Codigo de modelo de documento fiscal diferente de 59",
            "1455", "Assinatura do Aplicativo Comercial nao e valida.	Rejeicao: Assinatura do Aplicativo Comercial nao e valida.",
            "1457", "Regime Especial de Tributacao do ISSQN diferente de 1, 2, 3, 4 e 5	Rejeicao: Codigo de Natureza da Operacao para ISSQN invalido",
            "1459", "Descricao do produto ou servico em branco	Rejeicao: Codigo do produto ou servico em branco",
            "1460", "GTIN nao e valido	Rejeicao: GTIN do item (N) invalido",
            "1461", "Descricao do produto ou servico em branco	Rejeicao: Descricao do produto ou servico em branco",
            "1462", "CFOP nao e valido para CFe-SAT (diferente de 5xxx)	Rejeicao: CFOP nao e de Operacao de saida prevista para CF-e-SAT",
            "1463", "Unidade Comercial do produto ou servico em branco	Rejeicao: Unidade Comercial do produto ou servico em branco",
            "1464", "Quantidade comercial nao e maior ou igual a zero	Rejeicao: Quantidade Comercial do item (N) invalido.",
            "1465", "Valor unitario nao e maior ou igual a zero	Rejeicao: Valor Unitario do item (N)invalido.",
            "1467", "Regra de calculo invalida (diferente de \"A\" e \"T\")	Rejeicao: Regra de calculo do Item (N) invalido (diferente de \"A\" e \"T\")",
            "1468", "Valor do Desconto sobre item nao e maior ou igual a zero	Rejeicao: Valor do Desconto do item (N) invalido.",
            "1469", "Outras despesas acessorias sobre item nao e maior ou igual a zero	Rejeicao: Valor de outras despesas acessorias do item (N) invalido.",
            "1471", "Origem da mercadoria invalida (diferente de 0, 1, 2, 3, 4, 5, 6, 7, 8)	Erro Rejeicao: Origem da mercadoria do Item (N) invalido (diferente de 0, 1 ,2, 3, 4, 5, 6, 7, 8)",
            "1471", "Origem da mercadoria invalida (diferente de 0, 1, 2, 3, 4, 5, 6, 7, 8)	Erro Rejeicao: Origem da mercadoria do Item (N) invalido (diferente de 0, 1 , 2, 3, 4, 5, 6, 7, 8)",
            "1471", "Origem da mercadoria invalida (diferente de 0, 1, 2, 3, 4, 5, 6, 7, 8)	Erro Rejeicao: Origem da mercadoria do Item (N) invalido (diferente de 0, 1 , 2, 3, 4, 5, 6, 7, 8)",
            "1471", "Origem da mercadoria invalida (diferente de 0, 1, 2, 3, 4, 5, 6, 7, 8)	Rejeicao: Origem da mercadoria do Item (N) invalido (diferente de 0, 1 , 2, 3, 4, 5, 6, 7, 8)",
            "1472", "Tributacao do ICMS invalida (diferente de 00, 20, 90)	Erro Rejeicao: CST do Item (N) invalido (diferente de 00, 20, 90)",
            "1473", "Aliquota efetiva do imposto nao e maior ou igual a zero.	Rejeicao: Aliquota efetiva do ICMS do item (N) nao e maior ou igual a zero.",
            "1473", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota efetiva do ICMS do item (N) nao e maior ou igual a zero.",
            "1475", "Tributacao do ICMS invalida (diferente de 40 e 41 e 60)	Rejeicao: CST do Item (N) invalido (diferente de 40 e 41 e 60)",
            "1476", "Codigo de Situacao da Operacao ? Simples Nacional invalido (diferente de 102, 300, 400 e 500)	Rejeicao: Codigo de situacao da operacao - Simples",
            "1477", "Codigo de Situacao da Operacao ? Simples Nacional invalido (diferente de 900)	Rejeicao: Codigo de situacao da operacao - Simples Nacional ? do Item (N) invalido (diferente de 900)",
            "1478", "Codigo de Situacao Tributaria do PIS Invalido (diferente de 01, 02 e 05)	Rejeicao: Codigo de Situacao Tributaria do PIS Invalido (diferente de 01, 02 e 05)",
            "1479", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo do PIS do item (N) invalido",
            "1479", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo do PIS do item (N) invalido.",
            "1479", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo do PIS do item (N) invalido.",
            "1480", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS do item(N) nao e maior ou igual a zero.",
            "1480", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS do item (N) invalido.",
            "1480", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS do item (N) invalida.",
            "1482", "Codigo de Situacao Tributaria do PIS Invalido (diferente de 03)	Rejeicao: Codigo de Situacao Tributaria do PIS Invalido (diferente de 03)",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) nao e maior ou igual a zero.",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) invalido.",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) invalida",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) nao e maior ou igual a zero.",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) nao e maior ou igual a zero.",
            "1483", "Validacao de numero positivo ou igual a zero.	Rejeicao: Qtde Vendida do item (N) nao e maior ou igual a zero.",
            "1484", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS em R$ do item (N) nao e maior ou igual a zero.",
            "1484", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS em R$ do item (N) invalido.",
            "1484", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota do PIS em R$ do item (N) invalida",
            "1486", "Codigo de Situacao Tributaria do PIS Invalido(diferente de 04, 06, 07, 08 e 09)	Rejeicao: Codigo de Situacao Tributaria do PIS Invalido (diferente de 04, 06, 07, 08 e 09)",
            "1487", "Codigo de Situacao Tributaria do PIS invalido (diferente de 49)	Rejeicao: Codigo de Situacao Tributaria do PIS invalido (diferente de 49)",
            "1488", "Codigo de Situacao Tributaria do PIS Invalido (diferente de 99)	Rejeicao: Codigo de Situacao Tributaria do PIS Invalido (diferente de 99)",
            "1490", "Codigo de Situacao Tributaria da COFINS Invalido (diferente de 01, 02 e 05)	Rejeicao: Codigo de Situacao Tributaria da COFINS Invalido (diferente de 01, 02 e 05)",
            "1491", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo do COFINS do item (N) invalido.",
            "1491", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo da COFINS do item (N) invalido.",
            "1491", "Validacao de numero positivo ou igual a zero.	Rejeicao: Base de calculo da COFINS do item (N) invalido",
            "1492", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota da COFINS do item (N) nao e maior ou igual a zero.",
            "1492", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota da COFINS do item (N) nao e maior ou igual a zero.",
            "1492", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota da COFINS do item (N) nao e maior ou igual a zero.",
            "1494", "Codigo de Situacao Tributaria da COFINS Invalido (diferente de 03)	Rejeicao: Codigo de Situacao Tributaria da COFINS Invalido (diferente de 03)",
            "1496", "Validacao de numero positivo	Rejeicao: Aliquota da COFINS em R$ do item (N) nao e maior ou igual a zero",
            "1496", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota da COFINS em R$ do item (N) nao e maior ou igual a zero.",
            "1496", "Validacao de numero positivo ou igual a zero.	Rejeicao: Aliquota da COFINS em R$ do item (N) nao e maior ou igual a zero.",
            "1498", "Codigo de Situacao Tributaria da COFINS Invalido (diferente de 04, 06, 07, 08 e 09)	Rejeicao: Codigo de Situacao Tributaria da COFINS Invalido (diferente de 04, 06, 07, 08 e 09)",
            "1499", "Codigo de Situacao Tributaria da COFINS Invalido (diferente de 49)	Rejeicao: Codigo de Situacao Tributaria da COFINS Invalido (diferente de 49)",
            "1500", "Codigo de Situacao Tributaria da COFINS Invalido (diferente de 99)	Rejeicao: Codigo de Situacao Tributaria da COFINS Invalido (diferente de 99)",
            "1501", "Informado grupo de tributacao do ISSQN (id:U01) sem informar a IM (id:C13)	Rejeicao: Operacao com tributacao de ISSQN sem informar a Inscricao Municipal",
            "1503", "Validacao de numero positivo ou igual a zero.	Rejeicao: Valor das deducäes para o ISSQN do item (N) nao e maior ou igual a zero.",
            "1505", "Validacao de numero maior ou igual a 2,00 (2%) e menor ou igual a 5,00 (5%).	Rejeicao: Aliquota efetiva do ISSQN do item (N) nao e maior ou igual a 2,00 (2%) e menor ou igual a 5,00 (5%).",
            "1507", "Indicador de rateio do Desconto/Acrescimo sobre subtotal entre itens sujeitos a tributacao pelo ISSQN.	Rejeicao: Indicador de rateio para ISSQN invalido",
            "1509", "Se informada TAG, validacao de codigo diferente de brancos.	Rejeicao: Codigo municipal de Tributacao do ISSQN do Item (N) em branco.",
            "1510", "Natureza da Operacao de ISSQN diferente de 1, 2, 3, 4, 5, 6, 7 e 8	Rejeicao: Codigo de Natureza da Operacao para ISSQN invalido",
            "1511", "Indicador de Incentivo Fiscal do ISSQN diferente de 1 e 2	Rejeicao: Indicador de Incentivo Fiscal do ISSQN do item (N) invalido (diferente de 1 e 2)",
            "1527", "Codigo do Meio de Pagamento empregado para quitacao do CF-e-SAT	Rejeicao: Codigo do Meio de Pagamento invalido",
            "1528", "Valor do Meio de Pagamento empregado para quitacao do CF-e-SAT, numero menor ou igual a zero	Rejeicao: Valor do Meio de Pagamento invalido.",
            "1533", "Valor nao e maior ou igual a zero.	Rejeicao: Valor aproximado dos tributos do CFe_SAT negativo.",
            "1534", "Valor nao e maior ou igual a zero.	Rejeicao: Valor aproximado dos tributos do produto negativo.",
            "1535", "Codigo da credenciadora de cartao de debito ou credito diferente dos previstos no Anexo 3	Rejeicao: codigo da credenciadora de cartao de debito ou credito invalido",
            "1998", "Dados de entrada resultam em valores negativos.	Rejeicao: Nao e possivel gerar o cupom com os dados de entrada informados, pois resultam valores negativos.",
            "1999", "Erro desconhecido	Rejeicao: Erro nao identificado",
            "4000", "Ativado corretamente	SAT Ativado com Sucesso.",
            "4001", "Erro na criacao do certificado	Processo de ativacao foi interrompido.",
            "4002", "SEFAZ nao reconhece este SAT (CNPJ invalido)	Verificar junto a SEFAZ o CNPJ cadastrado.",
            "4003", "SAT/AC SAT ja ativado ou pendente de Vinculacao do AC	SAT disponivel para uso ou pendente de Vinculacao do AC.",
            "4004", "SAT com uso cessado	SAT bloqueado por cessacao de uso.",
            "4005", "SAT com uso cessado	Tentar novamente.",
            "4006", "CSR ICP-BRASIL criado com sucesso	Processo de criacao do CSR para certificacao ICPBRASIL com sucesso",
            "4007", "Erro na criacao do CSR ICP-BRASIL	Processo de criacao do CSR para certificacao ICPBRASIL com erro",
            "4098", "SAT em processamento.Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "4099", "Erro desconhecido na ativacao	Informar ao administrador.",
            "6000", "Emitido com sucesso + conteudo notas.	Retorno CF-e-SAT ao AC para contingencia.",
            "6001", "Codigo de ativacao invalido.	Verificar o codigo e tentar mais uma vez.",
            "6002", "SAT ainda nao ativado.	Efetuar ativacao.",
            "6003", "SAT nao vinculado ao AC	Efetuar vinculacao",
            "6004", "Vinculacao do AC nao confere	Efetuar vinculacao",
            "6005", "Tamanho do CF-e-SAT superior a 1.500KB	Dividir CF-e-SAT em dois ou mais documentos.",
            "6006", "SAT bloqueado pelo contribuinte	Nao e possivel realizar venda",
            "6007", "SAT bloqueado pela SEFAZ	Nao e possivel realizar venda",
            "6008", "SAT bloqueado por falta de comunicacao	Nao e possivel realizar venda ate ser restabelecida a comunicacao com a SEFAZ.",
            "6009", "SAT bloqueado, codigo de ativacao incorreto	Aguarde o numero de minutos conforme tabela de bloqueio em caso de tentativas erradas do codigo de ativacao",
            "6010", "Erro de validacao do conteudo.	Informar o erro de acordo com a tabela do item 6.3",
            "6098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "6099", "Erro desconhecido na emissao.	Informar o administrador.",
            "7000", "Cupom cancelado com sucesso + conteudo CFe-SAT cancelado.	Retorno conteudo CFe-SAT cancelado ao AC.",
            "7001", "Codigo ativacao invalido	Verificar o codigo e tentar mais uma vez.",
            "7002", "Cupom invalido	Informar o administrador.",
            "7003", "SAT bloqueado pelo contribuinte	Nao e possivel realizar venda",
            "7004", "SAT bloqueado pela SEFAZ	Nao e possivel realizar venda",
            "7005", "SAT bloqueado por falta de comunicacao	Nao e possivel realizar venda ate ser restabelecida a comunicacao com a SEFAZ.",
            "7006", "SAT bloqueado, codigo de ativacao incorreto	Aguarde o numero de minutos conforme tabela de bloqueio em caso de tentativas erradas do codigo de ativacao",
            "7007", "Erro de validacao do conteudo	Informar o erro de acordo com a tabela do item 6.3.2",
            "7098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "7099", "Erro desconhecido no cancelamento.	Informar o administrador.",
            "8000", "SAT em operacao.	Verifica se o SAT esta ativo.",
            "8098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "8099", "Erro desconhecido.	Informar o administrador.",
            "9000", "Emitido com sucesso	Gera e envia um cupom de teste para SEFAZ, para verificar a comunicacao.",
            "9001", "codigo ativacao invalido	Verificar o codigo e tentar mais uma vez.",
            "9002", "SAT ainda nao ativado.	Efetuar ativacao",
            "9098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "9099", "Erro desconhecido	Informar o administrador.",
            "10000", "Resposta com Sucesso.	Informacäes de status do SAT.",
            "10001", "Codigo de ativacao invalido	Verificar o codigo e tentar mais uma vez",
            "10098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "10099", "Erro desconhecido	Informar o administrador.",
            "11000", "Retorno da sessao processada	Retorna o conteudo da sessao consultada.",
            "11001", "Codigo ativacao invalido	Verificar o codigo e tentar mais uma vez.",
            "11002", "SAT ainda nao ativado.	Efetuar ativacao.",
            "11003", "Sessao nao existe.	AC deve executar a sessao novamente.",
            "11098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "11099", "Erro desconhecido.	Informar o administrador.",
            "12000", "Rede Configurada com Sucesso	Efetuada a configuracao da Rede",
            "12001", "Codigo ativacao invalido	Verificar o codigo e tentar mais uma vez.",
            "12002", "Dados fora do padrao a ser informado	Corrigir dados",
            "12098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "12099", "Erro desconhecido	Informar o administrador.",
            "13000", "Assinatura do AC Registrada	Confirmacao de recebimento da SEFAZ",
            "13001", "Codigo ativacao invalido	Verificar o codigo e tentar mais uma vez.",
            "13002", "Erro de comunicacao com a SEFAZ	Nao foi possivel enviar assinatura a SEFAZ",
            "13003", "Assinatura fora do padrao informado	Corrigir dados",
            "13004", "CNPJ da Software House + CNPJ do emitente assinado no campo ?signAC? difere do informado no campo ?CNPJvalue?	Corrigir dados",
            "13007", "CNPJ do emitente difere daquele constante da parametrizacao de uso.	Corrigir dados",
            "13098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "13099", "Erro desconhecido	Informar o administrador.",
            "14000", "Software Atualizado com Sucesso	Confirmacao de atualizacao do software do SAT",
            "14001", "Codigo de ativacao invalido.	Verificar o codigo e tentar mais uma vez.",
            "14002", "Atualizacao em Andamento	SAT em processo de Atualizacao. Aguardar.",
            "14003", "Erro na atualizacao	Nao foi possivel Atualizar o SAT.",
            "14004", "Arquivo de atualizacao invalido	Em casos onde o Hash do arquivo de atualizacao recebido pelo equipamento nao for valido.",
            "14098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao.",
            "14099", "Erro desconhecido	Informar o administrador.",
            "15000", "Transferencia completa	Arquivos de Logs extraidos",
            "15001", "Codigo de ativacao invalido.	Verificar o codigo e tentar mais uma vez.",
            "15002", "Transferencia em andamento	Aguardar termino de transmissao",
            "15098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "15099", "Erro desconhecido	Informar o administrador.",
            "16000", "Equipamento SAT bloqueado com sucesso.	Confirmacao de bloqueio do SAT.",
            "16001", "Codigo de ativacao invalido.	Verificar o codigo e tentar mais uma vez.",
            "16002", "Equipamento SAT ja esta bloqueado.	Equipamento SAT ja bloqueado.",
            "16003", "Erro de comunicacao com a SEFAZ	Nao foi possivel bloquear o Equipamento SAT.",
            "16004", "Nao existe parametrizacao de bloqueio disponivel. Verifique configuracäes na SEFAZ	O contribuinte nao configurou o Equipamento SAT para bloqueio na retaguarda",
            "16098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "16099", "Erro desconhecido	Informar o administrador.",
            "17000", "Equipamento SAT desbloqueado com sucesso.	Confirmacao de desbloqueio do SAT",
            "17001", "Codigo de ativacao invalido.	Verificar o codigo e tentar mais uma vez.",
            "17002", "SAT bloqueado pelo contribuinte. Verifique configuracäes na SEFAZ	Nao foi possivel desbloquear o Equipamento SAT. O contribuinte nao configurou o Equipamento SAT para desbloqueio na retaguarda",
            "17003", "SAT bloqueado pela SEFAZ	Nao foi possivel desbloquear o Equipamento SAT.",
            "17004", "Erro de comunicacao com a SEFAZ	Nao foi possivel desbloquear o Equipamento SAT.",
            "17098", "SAT em processamento.	Tente novamente. Em casos onde o SAT estiver processando outra funcao",
            "17099", "Erro desconhecido	Informar o administrador.",
            "18000", "Codigo de ativacao alterado com sucesso.	Confirmacao de troca do codigo de ativacao.",
            "18001", "Codigo de ativacao invalido.	Verificar o codigo atual e tentar mais uma vez.",
            "18002", "Codigo de ativacao de emergencia Incorreto.	Nao foi possivel alterar o codigo de ativacao.",
            "18098", "SAT em processamento. Tente novamente.	Em casos onde o SAT estiver processando outra funcao",
            "18099", "Erro desconhecido	Informar o administrador."
        };
    }
}
