BEGIN TRANSACTION T1

-- Ativação
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'chaveAtivacao', N'', NULL, 1, N'Chave de Ativação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'dtUltimaVerificacao', NULL, NULL, 1, NULL)
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'dtValidade', NULL, NULL, 1, NULL)

-- Configurações do Sistema
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'autSempre', N'1', N'0|1', 1, NULL)
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'creditoPadrao', N'0', NULL, 1, N'Crédito Padrão')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'imprimirPedidosDescontoFechamento', N'1', N'0|1', 1, N'Imprimir pedidos com desconto no Fechamento')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'imprimirProdutosCanceladosFechamento', N'1', N'0|1', 1, N'Imprimir Produtos Cancelados no Fechamento')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'imprimirProdutosVendidosFechamento', N'1', N'0|1', 1, N'Imprimir Produtos Vendidos no Fechamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'AliquotaPadrao', N'II', NULL, 1, N'Alíquota Padrão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'comandaComCheckin', N'1', N'0|1', 1, N'Comanda com Checkin')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'DDDPadrao', N'11', NULL, 1, N'DDD Padrão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImagemProdutoAltura', N'800', NULL, 1, N'Altura da Imagem do Produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImagemProdutoAlturaThumb', N'80', NULL, 1, N'Altura da Thumbnail da Imagem do Produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImagemProdutoLargura', N'1280', NULL, 1, N'Largura da Imagem do Produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImagemProdutoLarguraThumb', N'128', NULL, 1, N'Largura da Thumbnail da Imagem do Produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'integracao1', N'0', N'0|1', 1, N'Habilitar Integração 1')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'integracao2', N'0', N'0|1', 1, N'Habilitar Integração 2')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'limiteComanda', N'300', NULL, 1, N'Limite de gastos para Comanda')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'msgCupom', N'Sistema PDV7  www.pdvseven.com.br', NULL, 1, N'Mensagem do Cupom Fiscal')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'PermitirPedidoModificacaoInvalido', N'0', N'0|1', 1, N'Permitir Pedidos com Modificações Inválidas no Caixa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'PossuiCardapio', N'0', N'0|1', 1, N'Possui Cardápio')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'PossuiSAT', N'0', N'0|1', 1, N'Possui S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'SolicitarSenhaDesconto', N'1', N'0|1', 1, N'Solicitar senha de gerente para Desconto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'SolicitarTipoDesconto', N'1', N'0|1', 1, N'Solicitar tipo de Desconto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'SolicitarTipoDescontoItem', N'1', N'0|1', 1, N'Solicitar tipo de Desconto no Desconto por Item')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'taxaServicoBalcao', N'0', NULL, 1, N'Taxa de Serviço Balcão %')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'taxaServicoComanda', N'0', NULL, 1, N'Taxa de Serviço Comanda %')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'taxaServicoEntrega', N'0', NULL, 1, N'Taxa de Serviço Delivery %')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'taxaServicoMesa', N'10', NULL, 1, N'Taxa de Serviço Mesa %')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'toleranciaPagamento', N'0', NULL, 1, N'Tolerância no Pagamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ValidarPedidoModificacaoInvalido', N'1', N'0|1', 1, N'Validar Limites de Modificações no Caixa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'CaminhoXmlSat', N'C:\\PDVSeven\\SAT', N'', 1, N'Caminho para salvar os XMLs do S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImprimirViaControleDelivery', N'1', N'0|1', 1, N'Imprimir Via de Controle no Delivery')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ManterImpressaoPorDias', N'0', NULL, 1, N'Dias Para manter Ordens de Impressão No BD')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'MsgTicketPrePago', NULL, NULL, 0, N'Mensagem do Ticket Pré-Pago')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'SalvarXmlSat', N'0', N'0|1', 1, N'Salvar XMLs do S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'PainelModificacaoAvancado', N'0', N'0|1', 0, N'Exibir Painel de Modificação Avançado')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ExibirItensZeradosCaixaPreConta', N'0', N'0|1', 0, N'Exibir itens com valor zero no caixa e pre-conta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ServicoComoItem', N'1', N'0|1', 0, N'Ativar serviço como um item do pedido')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'DadosClienteCompletoOrdem', N'1', N'0|1', 0, N'Imprimir dados completos na ordem de produção')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ImprimirViaMotoboy', N'1', N'0|1', 0, N'Imprimir Via da conta para Motoboy no Delivery')

-- Relatório Fechamento
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-PedidosDescontoDetalhe', N'1', N'0|1', 1, N'Exibir Detalhes de Descontos')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-PedidosDescontoResumo', N'1', N'0|1', 1, N'Exibir Resumo de Descontos')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-ProdutosAbertos', N'1', N'0|1', 1, N'Exibir Produtos em Aberto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-ProdutosCancelados', N'1', N'0|1', 1, N'Exibir Produtos Cancelados')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-ProdutosVendidos', N'1', N'0|1', 1, N'Exibir Produtos Vendidos')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-ResumoCaixa', N'1', N'0|1', 1, N'Exibir Resumo por Caixa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'RelatorioFechamento-ResumoTipoPagamento', N'1', N'0|1', 1, N'Exibir Resumo por Tipo de Pagamento')

-- SAT
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_codigoAtivacao', N'123456789', NULL, 1, N'Código de Ativação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_det_prod_indRegra', N'A', N'A:Arredondamento|T:Truncamento', 1, N'Regra de Arredondamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_CNPJ', N'14200166000166', NULL, 1, N'CNPJ do Emitente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_cRegTrib', N'1', N'0|1', 1, N'Regime Tributário')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_cRegTribISSQN', N'1', N'0|1', 1, N'Regime especial de tributação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_IE', N'111111111111', NULL, 1, N'IE do Emitente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_IM', N'111111', NULL, 0, N'IM do Emitente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_emit_indRatISSQN', N'N', NULL, 1, N'Indicador de rateio do Desconto sobre subtotal entre itens sujeitos à tributação pelo ISSQN')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_ide_CNPJ', N'14200166000166', NULL, 1, N'CNPJ da Softwarehouse')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_ide_signAC', NULL, NULL, 1, NULL)
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_versaoDadosEnt', N'0.07', N'0.07:Versão 7|0.08:Versão 8', 1, N'Versão do XML')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_12741', N'1', N'0|1', 1, N'Imprimir Lei da Transparência no Cupom S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_UF', N'35', N'11:RO|12:AC|13:AM|14:RR|15:PA|16:AP|17:TO|21:MA|22:PI|23:CE|24:RN|25:PB|26:PE|27:AL|28:SE|29:BA|31:MG|32:ES|33:RJ|35:SP|41:PR|42:SC|43:RS|50:MS|51:MT|52:GO|53:DF', 0, N'UF')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_urlServicoSAT', NULL, NULL, 0, N'URL do WS S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_nome_fantasia', N'PDVSeven', NULL, 1, N'Nome Fantasia')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'infCFe_email_destinatario_padrao', N'', NULL, 1, N'Email para envio de CF-e')

-- MyFinance
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'intervaloSyncMyFinance', N'3600', NULL, 0, N'Intervalo que o serviço de integrações faz a sincronização com a API MyFinance (em segundos)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'dtUltimaSyncMyFinance', NULL, NULL, 0, N'Data da ultima sincornização do MyFinance')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'dtUltimaFechamentoPedidoMyFinance', NULL, NULL, 0, N'Data de fechamento do ultimo pedido enviado ao MyFinance')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ultimoIDPedidoMyFinance', NULL, NULL, 0, N'ID do ultimo pedido enviado ao MyFinance')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'ultimoIDPagamentoMyFinance', NULL, NULL, 0, N'ID do último pagamento enviado ao MyFinance')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'EnviadoMyFinance', N'0', N'0|1', 0, N' Flag que indica se o ultimo pagamento foi enviado com sucesso ao MyFinance')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (NULL, N'HabilitaMyFinance', N'0', N'0|1', 0, N' Flag que habilita integração MyFinance')


-- 10: Caixa
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'AbrirGaveta', N'0', N'0|1', 1, N'Abrir gaveta após cada venda')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'CupomSAT', N'elgin', N'elgin:Elgin|bematech:Bematech', 1, N'Modelo do Cupom S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'digitosCodigo', N'4', NULL, 1, N'Quantidade de Dígitos para o Código do produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'etiquetaBalanca', N'0', N'0|1', 1, N'Utiliza Balança Etiquetadora')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'GerarTicketPrePago', N'0', N'0|1', 1, N'Gerar Ticket Pré Pago')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'Log', N'C:\\PDV7\\log\\teste', NULL, 1, N'Caminho Log')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'LogAtivado', N'1', N'0|1', 1, N'Log Ativado')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'ManterPosicaoLista', N'0', N'0|1', 1, N'Manter posição selecionada na lista')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'ModeloImpressora', N'', NULL, 0, N'Nome da Impressora')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'ModoFiscal', N'0', N'0|1', 1, N'Modo Fiscal')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'OrdemImpressao', N'1', N'0|1', 1, N'Ordem Impressão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'PortaBalanca', N'COM1', NULL, 1, N'Porta da Balança')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'PortaImpressora', N'USB001', NULL, 1, N'Porta da Impressora')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'precoPeso', N'peso', N'peso:Peso|preco:Preço', 1, N'O que está sendo impresso na etiqueta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'ProtocoloBalanca', N'TOLEDO', N'TOLEDO|FILIZOLA', 1, N'Protocolo de comunicação da Balança')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'TipoGerenciadorImpressao', N'0', N'0:Sem Impressora|1:Impressora Windows|2:ACBr|4:S@T', 1, N'Tipo Gerenciador Impressão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'TipoImpressaoSat', N'Novo', N'Novo|Antigo', 1, N'Tipo Impressão S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'TipoPedidoPadrao', N'10', N'10:Mesa|20:Comanda|30:Delivery|40:Balcão', 0, N'Tipo de pedido Padrão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'VelocidadeImpressora', N'115200', N'9600:Serial|115200:USB', 1, N'Velocidade da Impressora')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'tipoPedidoBalcao', N'1', N'0|1', 1, N'Habilitar Tipo de Pedido Balcão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'tipoPedidoComanda', N'1', N'0|1', 1, N'Habilitar Tipo de Pedido Comanda')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'tipoPedidoEntrega', N'1', N'0|1', 1, N'Habilitar Tipo de Pedido Delivery')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'tipoPedidoMesa', N'1', N'0|1', 1, N'Habilitar Tipo de Pedido Mesa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (10, N'CaixaTouch', N'1', N'0|1', 1, N'Usar seleção touch no caixa')

-- 20: Terminal Android
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'senha', N'9999', NULL, 1, N'Senha para sair do programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'area', NULL, NULL, 1, N'Área de produção padrão (ID)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'askprice', N'0', N'0|1', 1, N'Solicitar preço quando preço é 0')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'autenticarsempre', N'1', N'0|1', 1, N'Sempre solicitar autenticação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'config', N'2606', NULL, 1, N'Senha para configurar o programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'impressaoconta', N'0', N'0|1', 1, N'Definir local imp. conta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'listimpressaoconta', N'-1', NULL, 1, N'Local de impressão de conta (ID)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'mostrarlista', N'1', N'0|1', 1, N'Exibir lista de produtos')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'mostrarresumo', N'1', N'0|1', 1, N'Exibir resumo do pedido')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'solicitarpessoas', N'1', N'0|1', 1, N'Solicitar info de fechamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'solicitarref', N'0', N'0|1', 1, N'Solicitar Referência')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'tipocliente', N'0', N'0:CPF/CNPJ|1:E-mail|2:Telefone', 1, N'Chave cliente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'usarareas', N'0', N'0|1', 1, N'Usar áreas de produção')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (20, N'wifi', N'1', N'0|1', 1, N'Extender Timeout')

-- 30: Terminal Windows
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'AutenticarSempre', N'1', N'0|1', 1, N'Sempre Solicitar Autenticação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'CodigoBarras', N'1', N'0|1', 1, N'Leitura de código de barras')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'digitosCodigo', N'4', NULL, 1, N'Quantidade de Dígitos para o Código do produto')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'EsconderComanda', N'0', N'0|1', 1, N'Esconder Comanda')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'EsconderMesa', N'0', N'0|1', 1, N'Esconder Mesa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'etiquetaBalanca', N'0', N'0|1', 1, N'Utiliza Balança Etiquetadora')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'Log', N'C:\\PDV7\\log', NULL, 1, N'Caminho Log')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'OrdemImpressao', N'1', N'0|1', 1, N'Ordem Impressão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'PortaBalanca', N'COM1', NULL, 1, N'Porta da Balança')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'precoPeso', N'peso', N'peso:Peso|preco:Preço', 1, N'O que está sendo impresso na etiqueta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (30, N'ProtocoloBalanca', N'TOLEDO', N'TOLEDO|FILIZOLA', 1, N'Protocolo de comunicação da Balança')

-- 40: Comanda Eletrônica
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'config', N'2606', NULL, 1, N'Senha para configurar o programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'area', NULL, NULL, 1, N'Área de produção padrão (ID)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'askprice', N'0', N'0|1', 1, N'Solicitar preço quando preço é 0')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'autenticarsempre', N'0', N'0|1', 1, N'Sempre solicitar autenticação')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'impressaoconta', N'0', N'0|1', 1, N'Definir local imp. conta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'listimpressaoconta', N'-1', NULL, 1, N'Local de impressão de conta (ID)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'mostrarlista', N'1', N'0|1', 1, N'Exibir lista de produtos')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'mostrarresumo', N'1', N'0|1', 1, N'Exibir resumo do pedido')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'senha', N'9999', NULL, 1, N'Senha para sair do programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'solicitarpessoas', N'1', N'0|1', 1, N'Solicitar info de fechamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'solicitarref', N'1', N'0|1', 1, N'Solicitar Referência')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'tipocliente', N'0', N'0:CPF/CNPJ|1:E-mail|2:Telefone', 1, N'Chave cliente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'usarareas', N'0', N'0|1', 1, N'Usar áreas de produção')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (40, N'wifi', N'1', N'0|1', 1, N'Extender Timeout')

-- 50: Controle Saída

-- 60: Cardápio Digital
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'area', NULL, NULL, 0, N'Área de produção padrão (ID)')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'askprice', N'0', N'0|1', 1, N'Solicitar preço quando preço é 0')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'autenticarsempre', N'0', N'0|1', 1, N'Sempre solicitar autenticação')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'mostrarlista', N'0', N'0|1', 1, N'Exibir lista de produtos')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'mostrarresumo', N'1', N'0|1', 1, N'Exibir resumo do pedido')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'solicitarref', N'1', N'0|1', 1, N'Solicitar Referência')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'usarareas', N'0', N'0|1', 1, N'Usar áreas de produção')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'wifi', N'1', N'0|1', 1, N'Extender Timeout')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'config', N'2606', NULL, 1, N'Senha para configurar o programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'senha', N'9999', NULL, 1, N'Senha para sair do programa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'senhamesa', N'555', NULL, 1, N'Senha para definir mesa')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'impressaoconta', N'0', N'0|1', 1, N'Definir local imp. conta')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'listimpressaoconta', N'-1', NULL, 1, N'Local de impressão de conta (ID)')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'solicitarpessoas', N'1', N'0|1', 1, N'Solicitar info de fechamento')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'tipocliente', N'0', N'0:CPF/CNPJ|1:E-mail|2:Telefone', 1, N'Chave cliente')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'usuario', N'2010', NULL, 1, N'ID do Usuário do cardápio')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (60, N'verifimagens', N'0', N'0|1', 1, N'Verificar por novas imagens')

-- 70: Controle de Estoque

-- 80: Gerenciador de Impressao
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (80, N'CupomSat', N'elgin', N'elgin:Elgin|bematech:Bematech', 1, N'Modelo do Cupom S@T')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (80, N'TipoImpressaoSat', N'Novo', N'Novo|Antigo', 1, N'Tipo Impressão S@T')

-- 90: Integração Tiny
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (90, N'codigo', N'1', N'0:Código do Produto|1:Código de Integração 1|2:Código de Integração 2', 1, N'Código para utilizar na integração')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (90, N'intervalo', N'1', NULL, 1, N'Intervalo (em minutos) de cada sincronização')
-- INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (90, N'token', N'', NULL, 1, N'Token de Integração do TinyERP')

-- 100: WebService
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (100, N'OrdemImpressao', N'1', N'0|1', 1, N'Ordem Impressão')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (100, N'SalvarXMLPedido', N'0', N'0|1', 1, N'Salvar XML da Pedido')
INSERT [dbo].[tbConfiguracaoBD] ([IDTipoPDV], [Chave], [Valor], [ValoresAceitos], [Obrigatorio], [Titulo]) VALUES (100, N'SalvarXMLRequisicoes', N'0', N'0|1', 1, N'Salvar XML da Requisição')

COMMIT TRANSACTION T1