// <auto-generated />
namespace a7D.PDV.BigData.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Query : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Query));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241221150_Query"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
