// <auto-generated />
namespace a7D.PDV.BigData.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Query_Nome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Query_Nome));
        
        string IMigrationMetadata.Id
        {
            get { return "201902132115035_Query_Nome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
