// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a7D.PDV.Iaago.WebApp.Models;

namespace a7D.PDV.Iaago.WebApp.Migrations
{
    [DbContext(typeof(IaagoContext))]
    [Migration("20190215150307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("a7D.PDV.Iaago.WebApp.Models.Pergunta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Criacao");

                    b.Property<string>("Entidade1")
                        .HasMaxLength(50);

                    b.Property<string>("Entidade2")
                        .HasMaxLength(50);

                    b.Property<string>("Entidade3")
                        .HasMaxLength(50);

                    b.Property<string>("Intencao")
                        .HasMaxLength(50);

                    b.Property<string>("Luis")
                        .HasMaxLength(50);

                    b.Property<double>("QTD");

                    b.Property<string>("Retorno")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("UltimaAtualizacao");

                    b.Property<DateTime>("UltimoUso");

                    b.Property<string>("Valor1")
                        .HasMaxLength(100);

                    b.Property<string>("Valor2")
                        .HasMaxLength(100);

                    b.Property<string>("Valor3")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
