
namespace a7D.PDV.Integracao.Pagamento.NTKPos
{
    public enum PTIINF : uint
    {
        OPERATION = 0x02, //Transaction that was performed: “00” – not defined “01” – Sale (payment) “02” – Administrative (general) “04” – Sale void 
        MERCHCNPJCPF = 0x1C, // CNPJ (ou CPF) do Estabelecimento / Ponto de captura
        TOTAMNT = 0x25, //Final transaction amount, in cents, with leading zeros. 
        CURRENCY = 0x26, //Currency code, according to ISO4217. 
        FISCALREF = 0x28, // Número da fatura (final nulo). Este parâmetro é opcional.
        CARDTYPE = 0x29, //Card type: “00” - Unknown “01” - Credit “02” - Debit “03” - Voucher “04” - Stored value “05” - Private Label 
        REQNUM = 0x32, //Unique transaction identifier (generated by the terminal). 
        AUTHSYST = 0x35, //Name of the acquirer/processor that processed the transaction. 
        VIRTMERCH = 0x36, //Merchant identifier for the terminal management system. 
        AUTMERCHID = 0x38, //Merchant identifier for the acquirer.
        FINTYPE = 0x3B, // Modalidade de financiamento da transação: 1: à vista; 2: parcelado pelo Emissor; 4: parcelado pelo Estabelecimento; 8: pré-datado; 16: crédito emissor; 32: Prédatado parcelado.
        INSTALLMENTS = 0x3C, // Quantidade de parcelas, para transações parceladas
        RESULT = 0x81, //Error code (if PTI_EFT_Exec returns PTIRET_EFTERR).
        RESULTMSG = 0x42, //Text message describing the result of the transaction (success or failure). 
        AUTLOCREF = 0x44, //Unique transaction identifier (generated by the terminal management system). 
        AUTEXTREF = 0x45, //Unique transaction identifier (generated by the acquirer/processor). 
        AUTHCODE = 0x46, //Authorization code (generated by the issuer). 
        CARDNAME = 0x4B, //Name of the card or issuer. 
        RCPTMERCHANT = 0x53, //up to 40 Receipt line – merchant copy (xxx>=0). 
        RCPTCHOLDER = 0x54, // up to 40 Receipt line – cardholded copy (xxx>=0). 
        TRNORIGDATE = 0x57, //Transaction date and time, format “YYMMDDhhmmss”. 
        TRNORIGNSU = 0x58, // Número de referência da transação original (atribuído pela adquirente/processadora). Este parâmetro é mandatório para transações de estorno (PTITRN_SALEVOID).
        TRNORIGAUTH = 0x62, // Código de autorização da transação original. Este campo é utilizado para transações de cancelamento.
        DATETIME = 0x31, // Horário do servidor PGWEB.
        TRNORIGTIME = 0x73, // Horário da transação original. Este campo é utilizado para transações de cancelamento. Formato HHMMSS.
        CARDENTMODE = 0xC0, //Card entry mode: “001”: manual PAN entry “002”: magstripe “004”: contact EMV “016”: fallback to magstripe “032”: contactless (magstripe simulated) “064”: contactless EMV
        CARDPARCPAN = 0xC8, //Masked PAN 
        CHOLDVERIF = 0xCF, //Cardholder verification method(s), sum of: “01”: signature “02”: PIN offline verification “04”: offline PIN was blocked during this transaction “08”: PIN online verification 
        MERCHADDDATA1 = 0xF0, // Número de referência da transação atribuído pela Automação Comercial. Caso fornecido, este número será incluído no histórico de dados da transação e encaminhado à adquirente/processadora, se suportado. Este parâmetro é opcional
        MERCHADDDATA2 = 0xF1, // Dados adicionais específicos do negócio. Caso fornecido, será incluso no histórico de dados da transação, por exemplo para referências cruzadas. Este parâmetro é opcional.
        MERCHADDDATA3 = 0xF2, //  Dados adicionais específicos do negócio. Caso fornecido, será incluso no histórico de dados da transação, por exemplo para referências cruzadas. Este parâmetro é opcional.
        MERCHADDDATA4 = 0xF3, //  Dados adicionais específicos do negócio. Caso fornecido, será incluso no histórico de dados da transação, por exemplo para referências cruzadas. Este parâmetro é opcional.
    }

    public enum PTIPAR : uint
    {
        AMOUNT = 6, //up to 12 Transaction amount, in cents. This parameter is mandatory for sale (PTITRN_SALE) and void (PTITRN_SALEVOID) transactions.
        CURRENCY = 7, // 3 Currency code, according to ISO4217(840 for US Dollars). This parameter is required if PTIPAR_AMOUNT is informed.
        POSREF = 41, // up to 128 Transaction reference number assigned by the POS software.If provided, this number will be included in the transaction historical data and forwarded to the acquirer/processor, if supported.This parameter is optional.
        ADDDATA2 = 42, //up to 128 Business-specific additional data.If provided, it will be included in the transaction historical data, for example for cross-reference.This parameter is optional.
        ADDDATA3 = 43, //up to 128 Business-specific additional data.If provided, it will be included in the transaction historical data, for example for cross-reference.This parameter is optional.
        ADDDATA4 = 44, //up to 128 Business-specific additional data.If provided, it will be included in the transaction historical data, for example for cross-reference.This parameter is optional.
        INVOICE_NO = 46, //up to 12 Invoice number(null-terminated). This parameter is optional.
        ORIGAUTEXTREF = 47, //up to 50 Original transaction reference number(assigned by the acquirer/processor). This parameter is mandatory for void (PTITRN_SALEVOID) transactions.
        ORIGDATE = 48, // 7 Original transaction date (assigned by the acquirer/processor). 
        ORIGAUT = 49, //7 Original transaction authorization code (assigned by the acquirer/processor). 
        ORIGTIME = 50, //7 Original transaction time (assigned by the acquirer/processor). 
        MERCHCNPJCPF = 51, //up to 15 Tax ID of the merchant. 
        INSTALLMENTS = 52, //up to 2 Number of installments. 
        FINTYPE = 53, //up to 2 Transaction financing mode: 1: in cash; 2: in installments (issuer); 4: in installments (merchant); 8: pre-dated. 
        CARDTYPE = 54, //up to 20 Type of card to be used: 1: credit; 2: debit; 4: voucher; 8: other. 
        AUTHSYST = 55 //up to 20 Service provider. 
    }

    public enum PTICNF : uint
    {
        SUCCESS = 1,// Transaction is confirmed. 
        PRINTERR = 2, //Printer error, reverse transaction. 
        DISPFAIL = 3,//Error with the dispenser mechanism, reverse transaction. 
        OTHERERR = 4 //Other error, reverse transaction. 
    }

    public enum PTIPRN : uint
    {
        MERCHANT = 1,  //Merchant copy
        CHOLDER = 2, //Cardholder copy
        //BOTH = 3 //Print both
    }

    public enum PTIRET : int
    {
        ERRO_INTERNO = 99, //Erro desta aplicação
        OK = 0, //Successful operation. 
        INVPARAM = -2001, //Invalid parameter passed to the function. 
        NOCONN = -2002, //The terminal is offline. 
        BUSY = -2003, //The terminal is busy processing another command. 
        TIMEOUT = -2004, //User failed to press a key during the specified time. 
        CANCEL = -2005, //User pressed the [CANCEL] key. 
        NODATA = 2006, //Required information is not available. 
        BUFOVRFLW = -2007, //Data is larger than the provided buffer size. 
        SOCKETERR = -2008, //Unable to start listening to the specified TCP ports. 
        WRITEERR = -2009, //Unable to use the specified directory. 
        EFTERR = -2010, //The EFT operation was completed, but failed. 
        INTERNALERR = -2011, //Integration library internal error.
        PROTOCOLERR = -2012, //Communication error between the integration library and the terminal.
        SECURITYERR = -2013, //The function failed for security reasons.
        PRINTERR = -2014, //Printer error. 
        NOPAPER = -2015, //Printer out of paper. 
        NEWCONN = -2016, //New terminal connected.
        NONEWCONN = -2017, //No new connections received.
        NOTSUPPORTED = -2057, //Function not supported by the terminal. 
        CRYPTERR = -2058, //Data encryption error (communication between integration library and terminal). 
    }

    public enum PTITRN : uint
    {
        SALE = 0x21, //Payment of goods or services. 
        ADMIN = 0x20, //Any transaction that is not a payment (void, refund, preauthorization, report, receipt reprinting, etc.). 
        SALEVOID = 0x22 //Voids a sale transaction that was previously performed and confirmed.
    }

    public enum PTIFINTYPE : int
    {
        //Transaction financing mode:
        in_cash = 1,
        in_installments_issuer = 2,
        in_installments_merchant = 4,
        pre_dated = 8
    }

    public enum PTICARDTYPE : int
    {
        Unknown = 00,
        Credit = 01,
        Debit = 02,
        Voucher = 03,
        Stored_Value = 04,
        Private_Label = 05
    }

    public enum CODESYMB : int
    {
        EAN13 = 1,/* não implementado */
        _128 = 2,
        ITF14 = 3,
        QRCODE = 4
    }
}
