// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace a7D.PDV.WS2API
{
    using Microsoft.Rest;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Configuracao operations.
    /// </summary>
    public partial interface IConfiguracao
    {
        /// <param name='chaves'>
        /// </param>
        /// <param name='tipoPDV'>
        /// </param>
        /// <param name='idPDV'>
        /// </param>
        /// <param name='sistema'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> LerChavesWithHttpMessagesAsync(IList<string> chaves, int? tipoPDV = default(int?), int? idPDV = default(int?), bool? sistema = default(bool?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
