// <auto-generated />
namespace a7D.PDV.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2_19_A_Saldos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_19_A_Saldos));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191259197_2_19_A_Saldos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
