// <auto-generated />
namespace a7D.PDV.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2_21_Ticket_Integracoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_21_Ticket_Integracoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201906100032210_2_21_Ticket_Integracoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
