// <auto-generated />
namespace a7D.PDV.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2_23_FlagPermitirAlterar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_23_FlagPermitirAlterar));
        
        string IMigrationMetadata.Id
        {
            get { return "202203141827163_2_23_FlagPermitirAlterar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
