// <auto-generated />
namespace a7D.PDV.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2_29_CorrigeReservaNumeroNFCe : IMigrationMetadata
    {
        // Esta migration não altera o modelo EF. Reutiliza o snapshot da migration
        // imediatamente anterior para não duplicar um recurso de aproximadamente 90 KB.
        private readonly ResourceManager resources =
            new ResourceManager(typeof(_2_28_FixSequenciaNFCe));

        string IMigrationMetadata.Id
        {
            get { return "202609031900000__2_29_CorrigeReservaNumeroNFCe"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return resources.GetString("Target"); }
        }
    }
}
