using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MuxxLib.Enum_s
{
    public enum PWRET : short
    {
        INVALID = -1,
        #region Erros Gerais
        OK = 0,
        FROMHOSTPENDTRN = -2599,
        FROMHOSTPOSAUTHERR,
        FROMHOSTUSRAUTHERR,
        FROMHOST,
        TLVERR,
        SRVINVPARAM,
        REQPARAM,
        HOSTCONNUNK,
        INTERNALERR,
        BLOCKED,
        FROMHOSTTRNNFOUND,
        PARAMSFILEERR,
        NOCARDENTMODE,
        INVALIDVIRTMERCH,
        HOSTTIMEOUT,
        CONFIGREQUIRED,
        HOSTCONNERR,
        HOSTCONNLOST,
        FILEERR,
        PINPADERR,
        MAGSTRIPEERR,
        PPCRYPTERR,
        SSLCERTERR,
        SSLNCONN,
        GPRSATTACHFAILED,
        EMVDENIEDCARD,
        EMVDENIEDHOST,
        NOLINE,
        NOANSWER,
        SYNCERROR,
        CRCERR,
        DECOMPERR,
        PROTERR,
        NOSIM,
        SIMERROR,
        SIMBLOCKED,
        PPPNEGFAILED,
        WIFICONNERR,
        WIFINOTFOUND,
        #endregion

        #region Erros específicos da biblioteca
        INVPARAM = -2499,
        NOTINST,
        MOREDATA,
        NODATA,
        DISPLAY,
        INVCALL,
        NOTHING,
        BUFOVFLW,
        CANCEL,
        TIMEOUT,
        PPNOTFOUND,
        TRNNOTINIT,
        DLLNOTINIT,
        FALLBACK,
        WRITERR,
        PPCOMERR,
        NOMANDATORY,
        OFFINTERNAL,
        OFFINVCAP,
        OFFNOCARDENTMODE,
        OFFINVCARDENTMODE,
        OFFNOTABLECARDRANGE,
        OFFNOTABLEPRODUCT,
        OFFINVTAG,
        OFFNOCARDFULLPAN,
        OFFINVCARDEXPDT,
        OFFCARDEXP,
        OFFNOTRACKS,
        OFFTRACKERR,
        OFFCHIPMANDATORY,
        OFFINVCARD,
        OFFINVCURR,
        OFFINVAMOUNT,
        OFFGREATERAMNT,
        OFFLOWERAMNT,
        OFFGREATERINST,
        OFFLOWERINST,
        OFFINVCARDTYPE,
        OFFINVFINTYPE,
        OFFINVINST,
        OFFGREATERINSTNUM,
        OFFLOWERINSTNUM,
        OFFMANDATORYCVV,
        OFFINVLASTFOUR,
        OFFNOAID,
        OFFNOFALLBACK,
        OFFNOPINPAD,
        OFFNOAPOFF,
        OFFTRNNEEDPP,
        OFFCARDNACCEPT,
        OFFTABLEERR,
        OFFMAXTABERR,
        OFFINTERNAL1,
        OFFINTERNAL2,
        OFFINTERNAL3,
        OFFINTERNAL4,
        OFFINTERNAL5,
        OFFINTERNAL6,
        OFFINTERNAL7,
        OFFINTERNAL8,
        OFFINTERNAL9,
        OFFINTERNAL10,
        OFFINTERNAL11,
        OFFNOPRODUCT
        #endregion

    }
}
